// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHoYAPF7f-OO7l9xKs3MEL2V0A935WM8',
    appId: '1:642336805636:android:c5e88f9f6fed22bdac3651',
    messagingSenderId: '642336805636',
    projectId: 'zoned-express-7c5a1',
    databaseURL: 'https://zoned-express-7c5a1-default-rtdb.firebaseio.com',
    storageBucket: 'zoned-express-7c5a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4PnVvL3_4rcIYDYR4hapMg3PFY003lI',
    appId: '1:642336805636:ios:e3ffd9bcdede49d0ac3651',
    messagingSenderId: '642336805636',
    projectId: 'zoned-express-7c5a1',
    databaseURL: 'https://zoned-express-7c5a1-default-rtdb.firebaseio.com',
    storageBucket: 'zoned-express-7c5a1.appspot.com',
    iosClientId: '642336805636-d00cd4plpmn1dd55tp62g0g5ldp63b5t.apps.googleusercontent.com',
    iosBundleId: 'com.walidhamdi.zonedexpress',
  );
}
